#! python

def build(ctx):
    ctx.recurse('data_management')
    ctx.recurse('analysis')
    ctx.add_group()
    ctx.recurse('final')
    # # Safety measure -- else the LaTeX scanner might fail because some
    # # '.tex'-source file has not been generated.
    # ctx.add_group()
    # ctx.recurse('paper')
